; Exercise 1.15. The sine of an angle (specified in radians) can be computed by making use of the approximation sin x ~ x if x is sufficiently small, and the trigonometric identity sin(x) = 3sin(x/3) - 4sin^3(x/3) to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered ‘‘sufficiently small’’ if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:
(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
(p (sine (/ angle 3.0)))))

; Q: How many times is the procedure p applied when (sine 12.15) is evaluated?
; (sine 12.15) =
; (p (sine 4.05)) =
; (p (p (sine 1.35))) =
; (p (p (p (sine 0.45)))) =
; (p (p (p (p (sine 0.15))))) =
; (p (p (p (p (p (sine 0.05))))))
; (p (p (p (p (p 0.05)))))
; The answer is five.

; Q: What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?
; To answer this question, we need to find an answer to the following question:
; How many divisions by 3 do we need to do to the input in order to reach the base case?
; i.e. a/3^k <= 0.1
; 10a <= 3^k
; log(10a) / log(3) <= k
; We expressed k in terms of logarithm with respect to a, so, we need to do logarithmic number of steps.
; Thus, the function grows logarithmically.
